### ISSUE TITLE
Workflows do not derive the pnpm / node versions from the repo/envirnoment/config files.

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/create-release-plan-setup#111]
hard-coding version 8 has broken everyone to upgrading to version 9.

For now, I've been replacing this with a GH action that does all this for me:
```
- uses: wyvox/action-setup-pnpm@v3
```
it's been much less brittle because it reads all the places pnpm version can be set

Been doing this on a few PRs:
- https://github.com/NullVoxPopuli/ember-composable-helpers/pull/6
- https://github.com/proposal-signals/signal-polyfill/pull/4/commits/0babd8cb7f2e550fa2770c45a72982366e76a677

![image](https://github.com/embroider-build/create-release-plan-setup/assets/199018/87dbb476-1471-4345-9a97-d695ddca2534)

**Comment by mansona** [comment]
This has been fixed in https://github.com/embroider-build/create-release-plan-setup/pull/127

If you provide a packageManager we will use it 🎉
